#!/usr/bin/env node

var fs = require('fs');
var homedir = process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE;
var markName=process.argv[2]||"default";
var markFile=homedir+"/.marked_destinations";
var markSet;

try {
	markSet = JSON.parse(fs.readFileSync(markFile, {encoding: 'utf8'}));
}catch(e){
	process.exit("no marked destinations found");
}

process.stdout.write(markSet[markName]);
